title: "Nandini Rathore"
description: "Data Engineer | Azure | ETL | Cloud | SQL | Synapse | Databricks"

url: "https://nandinirana23.github.io"
baseurl: "/nandinirathore.github.io"

name: "Nandini Rathore"
role: "Data Engineer & ETL Developer"
email: "rathorenandini2310@gmail.com"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

social_links:
  linkedin: "https://linkedin.com/in/nandinirana23"
  github: "https://github.com/nandinirana23"
  email: "mailto:rathorenandini2310@gmail.com"

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

show_downloads: false
